import type { Metadata } from "next";
import "./globals.scss";
import { Inter } from 'next/font/google'

const inter = Inter({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  display: 'swap',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
